package shared;

public enum MessageType {
    LOGIN, LOGIN_SUCCESS, LOGIN_FAILED,
    CHALLENGE, CHALLENGE_ACCEPTED, CHALLENGE_REJECTED,
    MOVE, GAME_OVER, 
    PLAYER_LIST, HISTORY_REQUEST, HISTORY_RESPONSE,
    ERROR, DISCONNECT
}